web: &web
  build: .
  environment:
    - "DB_HOST=db"
    - "DB_PORT=5432"
    - "DB_PASSWORD=${DB_PASS}"
    - "DB_USER=${DB_USER}"
    - "DB_NAME=${DB_USER}"
  volumes:
    - ".:/opt/app/"
  links:
    - "db"
    - "memcached"

gunicorn:
  <<: *web
  entrypoint: ["gunicorn"]
  expose: ["8888"]
  volumes:
    - ".:/opt/app"
  command:
    - "myblog.wsgi:application"
    - "-w"
    - "4"
    - "--bind"
    - "0.0.0.0:8888"

dev:
  <<: *web
  command: ["runserver", "0.0.0.0:8000"]
  ports:
    - "80:8000"

nginx:
  image: "nginx:1.12.2"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  volumes_from:
    - "gunicorn"
  links:
    - "gunicorn"
  volumes_from:
    - "gunicorn:rw"
  ports:
    - "80:80"

node: &node
  image: "node:9.8.0"
  working_dir: "/opt/node"
  volumes:
    - ".:/opt/node"
  entrypoint: ["node"]

npm:
  <<: *node
  entrypoint: ["npm"]

gulp:
  <<: *node
  entrypoint: ["node", "node_modules/gulp/bin/gulp.js"]

db:
  image: "postgres:10.3"
  expose:
    - "5432"
  ports:
    - "5432:5432"
  volumes:
    - "/opt/myblog/postgresql:/var/lib/postgresql/data"
  environment:
    - "POSTGRES_PASSWORD=${DB_PASS}"
    - "POSTGRES_USER=${DB_USER}"
    - "POSTGRES_DB=${DB_NAME}"

memcached:
  image: "memcached:1.4.36"
  expose:
    - "11211"
  ports:
    - "11211:11211"
