# Generated by Django 2.0.1 on 2018-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_es',
            field=models.TextField(default=''),
        ),
    ]
