# Generated by Django 2.0.1 on 2018-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180505_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
